# Generated by Django 4.1.5 on 2023-01-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_project_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
