# Generated by Django 4.1.5 on 2023-01-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_work_company_link_work_end_date_work_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='company_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateField(default=''),
        ),
    ]
