# Generated by Django 4.1.5 on 2023-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_project_project_link_alter_work_company_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='company_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
