# Generated by Django 4.1.5 on 2023-01-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_project_project_link_alter_work_company_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
