# Generated by Django 4.1.7 on 2023-03-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="preview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
