# Generated by Django 4.1.7 on 2023-03-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_post_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
